### ISSUE TITLE
I want to know witch version of the VTK does vtkKinship support ?

### ISSUE THREAD

**Issue by xiaobo2014** [jeromevelut/vtkKinship#4]
I want to know the VTK version of vtkKinship. thank you.

**Comment by docyang** [comment]
I have made this project, but got blank under bin filepath. Do you wish to obtain curved mpr image from CTA? Maybe, we can communicate.

**Comment by djelouze** [comment]
Hi,

sorry for the huge silence.

vtkKinship was intended a long time ago for VTK5. Some filters have been made available for VTK6 though.

vtkKinship is a messy compilation of very specialized filters. Which one is useful for you ?

My work on curved MPR (SplineDrivenImageSlicer) has been made available as a VTK module now, so I won't maintain it from github.

**Comment by xiaobo2014** [comment]
I'm using VTK6 for now, and it work fine for vtkKinship. Thank you very much.

**Comment by docyang** [comment]
@xiaobo2014 May I ask you a few questions about Curved Planar Reformation? I have original CTA dcm data and labeled centerline of the artery, and I would like to obtain CPR images and the transformation between original data and CPR data. Could you give me some help? Thank you.

**Comment by xiaobo2014** [comment]
@docyang In my opinion, you can open a new issue about the question. And I will give you some help in my power.

**Comment by docyang** [comment]
Thank your for your help. New to C++....
