### ISSUE TITLE
How to convert this implementation to vtk with python interface?

### ISSUE THREAD

**Issue by docyang** [jeromevelut/vtkKinship#6]
I have original CTA dcm data and labeled centerline of the artery, and I would like to obtain 3D CPR volume and the transformation between original data and CPR data.

**Comment by djelouze** [comment]
Hi, 
I am a little bit confused, as the title of the issue does not reflect the description :/

If you want to use VTK, you can load your dicom with GDCM or vtk-dicom (you can find them on github). I think they are wrapped to python, it should fit your needs.

Regarding the CPR, my work was originally dedicated to straightened version. Have a look there, it's an old paper I wrote about this class (http://www.vtkjournal.org/browse/publication/838)

BTW, I recenty found that VTK had now an optional SplineDriveImageSlicer module, which that Kitware has an eye on it.

**Comment by docyang** [comment]
Thank you for your help!
